name: postman-pull-request
on: [push, pull_request] 
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Check out Git repositor
      uses: actions/checkout@v1
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org/
    - name: Install newman
      run: |
         npm install -g newman
         npm install -g newman-reporter-htmlextra
    #- name: Make Directory for results
     # run: mkdir -p testResults
    - name: Run the API and Postman's tests
      run: | 
       newman run Crosnetworkupdated.postman_collection.json -e Crosnetwork.postman_environment.json -r htmlextra --reporter-htmlextra-export
    - name: Output the run Details
      uses: actions/upload-artifact@v2
      with:
          name: RunReports
          # path: testResults
