name: postman-pull-request
on: [push, pull_request] 
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: [4.2]
    steps:
    - name: Check out Git repositor
      uses: actions/checkout@v1
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org/
    - name: Install newman
      run: npm install -g newman
    - name: Run the API and Postman's tests
      run: | 
        npm run start:dev &
        sleep 60
        npm install -g newman-reporter-htmlextra
        newman run Example.postman_collection.json --reporters htmlextra --reporter-htmlextra-title "testdemo"
      env:
        NODE_ENV: "develop"
